# Generated by Django 2.2.1 on 2019-05-17 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190517_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.DecimalField(decimal_places=5, max_digits=10, verbose_name='Peso'),
        ),
    ]
